[application]

# App (Project) Name
name = "chap-app"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# not working in 0.6.1
# `build` & `serve` dist path
# out_dir = "docs"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "chap-app"

# The application will be served at domain.com/my_application/, so we need to modify the base_path to the path where the application will be served
# comment this for local test
base_path = "ChapApp"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

# for local test
# style = ["./assets/main.css"]

# for hosting on github pages
style = ["./ChapApp/assets/main.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
