[package]
name = "webapp"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chap = "2.2.2"
dioxus = "0.4.0"
dioxus-web = "0.4.0"